### ISSUE TITLE
How to change input to Flask request.form

### ISSUE THREAD

**Issue by zachary** [mmohades/Venmo#12]
def __ask_user_for_otp_password():

this function only get value from input(), but how to change to get this from web

thanks

**Comment by mmohades** [comment]
Can you elaborate on "getting input from web"?

**Comment by zachary** [comment]
Thanks for updated, 
I mean the api wait 6 digital text code with python input('xxx'), how to change this to get 6 codes from web html <input type=text >

**Comment by mmohades** [comment]
That's not possible as of now. However, I think it's a good idea to make the authentication process more flexible to be implemented differently.
I'll make some changes this weekend, and let you know how you can do it.

**Comment by zachary** [comment]
Thanks for you updated.

I added new function as below, please advised it.

def __get_user_for_otp_password(self,username):
        otp = ""
        i=0
        while len(otp) < 6 or not otp.isdigit():
            if i>6:
                sys.exit('no')
            else:
                i=i+1
                time.sleep(30)
                r = redis.Redis(host='localhost',port=6379,db=0)
                otp = r.get(username)
        return otp

**Comment by zachary** [comment]
I added a function like this without @staticmethod

def __get_user_for_otp_password(self,username):
        otp = ""
        i=0
        while len(otp) < 6 or not otp.isdigit():
            if i>6:
                sys.exit('no')
            else:
                i=i+1
                time.sleep(30)
                r = redis.Redis(host='localhost',port=6379,db=0)
                otp = r.get(username)
        return otp

**Comment by mmohades** [comment]
I've released version 0.2.0 with the changes. Run `pip3 install venmo-api --upgrade` to update to the new version.
