### ISSUE TITLE
typo: "Baerer" token

### ISSUE THREAD

**Issue by correy** [mmohades/Venmo#15]
https://github.com/mmohades/Venmo/blob/9fdf5fdd106d35906729ffd69f424d3540bc81d2/venmo_api/utils/api_util.py#L16

Just noticed a typo while reading through.

**Comment by correy** [comment]
It must not be affecting anything in the API haha :)

**Comment by mmohades** [comment]
Thanks for opening an issue! I've fixed it in the new version. :)
