### ISSUE TITLE
Unable to parse transaction list with rejected user transactions

### ISSUE THREAD

**Issue by doctortickle** [mmohades/Venmo#2]
I have seen issue #1 and am having similar issues. However, my `venmo-api` is up to date. Of note, I have both a bank transaction and a recent transaction (within 5 hours) in my Venmo account. Not sure if this may be interfering. Seems to be an issue with `date_completed` again.

I don't know exactly what I'm doing wrong, but here's my code:

```
from venmo_api import Client

access_token = Client.get_access_token(username='User', password='Password')

venmo = Client(access_token=access_token)
me = venmo.user.get_my_profile()
myid = me.id

for transaction in venmo.user.get_user_transactions(myid):
    print(transaction.note)
```

This produces the error:

```
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    for transaction in venmo.user.get_user_transactions(str(myid)):
  File "/usr/local/lib/python3.7/site-packages/venmo_api/apis/user_api.py", line 149, in get_user_transactions
    return deserialize(response=response, data_type=Transaction)
  File "/usr/local/lib/python3.7/site-packages/venmo_api/utils/api_util.py", line 43, in deserialize
    return __get_objs_from_json_list(json_list=data, data_type=data_type)
  File "/usr/local/lib/python3.7/site-packages/venmo_api/utils/api_util.py", line 77, in __get_objs_from_json_list
    data_obj = data_type.from_json(obj)
  File "/usr/local/lib/python3.7/site-packages/venmo_api/models/transaction.py", line 42, in from_json
    date_completed = string_to_timestamp(parser.get_date_completed())
  File "/usr/local/lib/python3.7/site-packages/venmo_api/models/json_schema.py", line 51, in get_date_completed
    return self.payment[payment_json_format['date_completed']]
TypeError: 'NoneType' object is not subscriptable
```

I know that I have my own transactions. `get_user_transactions` works just fine for any other ID I use that is not my own.

Great project by the way, excited to use it. I'm setting up a refrigerator at work where people can take snacks and pay me by Venmo. I want to automate pushing transactions with a specific note to a Google Sheet.

EDIT:
Hey, I did some further digging by incrementing the `count` parameter. I found that it works great iterating through my own transaction list up until I encountered a transaction that reads "The user didn't accept your money." 

Similar to how Venmo includes bank transactions in the transaction list, they also include rejected user payments. Don't know how to fix this bug!

**Comment by mmohades** [comment]
Thank you for opening an issue. I'm trying to reproduce it and then fix it.

**Comment by mmohades** [comment]
That's a great idea! You could make a vending machine that venmoes you the purchases. :))
I tried to reproduce the bug, but I think I think didn't understand what you meant correctly. Can you please clarify what you mean by "rejected payments"? 
I **requested** money from someone, and she rejected it. I did it vice versa, but for both cases, they don't show up in my transactions list. It must be something else.

**Comment by doctortickle** [comment]
> That's a great idea! You could make a vending machine that venmoes you the purchases. :))
> 
> I tried to reproduce the bug, but I think I didn't understand what you meant correctly. Can you please clarify what you mean by "rejected payments"? How can I reproduce one?
> 
> I **requested** money from someone, and she rejected it. I did it vice versa, but for both cases, they don't show up in my transactions list. It must be something else.

Here is a picture of the transaction that is causing the error!

![image](https://user-images.githubusercontent.com/24944685/83190189-ba25ca00-a0cd-11ea-94b9-a80dbbed5dd0.jpeg)

**Comment by mmohades** [comment]
Thanks for the screen shot! This happens when a user uses iMessage for sending/requesting money. I'm trying to reproduce it and will fix it soon.

**Comment by mmohades** [comment]
Thanks for reporting the bug. Payments made on iMessage are a little different. They can become "refunds" if they get canceled or they can stay "pending" for a while until they expire and automatically get rejected. It should be fixed now. I haven't pushed an update on PyPi. I'll do that after checking your pull request.

**Comment by mmohades** [comment]
I have pushed the update on PyPi. Update your package using `pip3 install venmo-api --upgrade` and please let me know if the bug is fixed.

**Comment by doctortickle** [comment]
The issue is resolved. Thank you!

**Comment by mmohades** [comment]
@doctortickle Your detailed explanation helped me fixed the bug. Thank you.
