### ISSUE TITLE
Venmo getting a user ID?

### ISSUE THREAD

**Issue by negentropic** [mmohades/Venmo#22]
This is probably a dumb question but where do I get the user id or user
When using:
<img width="1249" alt="Screen Shot 2020-10-24 at 3 24 11 PM" src="https://user-images.githubusercontent.com/18454816/97094795-06d5e880-160d-11eb-9190-7e19716ba4eb.png">

`target_user='@name-user'`
or
`target_user_id='@name-name'`

I'm getting errors inputting strings. I'm doing something wrong.  I also do not see numeric IDs with usernames

**Comment by negentropic** [comment]
I think i just solved this with

`name_id = venmo.user.get_user('username')`

**Comment by mmohades** [comment]
For the `get_user` method, you must pass a userId to it to get the User information. A userId is the uniqeue identification made by Venmo for query purposes. If you have a `username`, and want to get the userId/User object for it, refer to #21.
