### ISSUE TITLE
venmo.payment.send_money returns True but fails to make payment

### ISSUE THREAD

**Issue by nickshep** [mmohades/Venmo#23]
When running `venmo.payment.send_money(13.68, "thanks for the 🍔", id)` with my id I get an error saying you can't pay yourself, but when I enter another user's id, the function returns true but never processes payment. 

This function was working a week ago and randomly broke. I tried logging out (revoking access token) and re-logging to no avail. The request function works perfectly, every-time. Is this possibly a security feature on the Venmo side?

I'm using Python 3.8.4 with the repository posted here. I installed using the setup.py script.

**Comment by mmohades** [comment]
Sending money still works. Maybe you're providing a wrong `id`? Or, there can be a problem with the default payment method. Also, check your transactions to that user and see if it went through:
```
transactions = client.user.get_transaction_between_two_users(client.my_profile().id, id)
for transaction in transactions:
    print(transaction)
```

Also, see how your payment methods look like:
```
p_methods = client.payment.get_payment_methods()
for p_method in p_methods:
    print(p_method)
```
Is the default payment method, Venmo balance?

**Comment by nickshep** [comment]
Hello! Thanks for the quick response.

I didn't check the default payment method. I transferred my balance to my bank which is why payments stopped sending. I will close this issue now.

**Comment by mmohades** [comment]
Thanks for opening an issue.
oh I see. I should probably raise an error when the balance is not enough. I'll take this into account.
