### ISSUE TITLE
User.phone returning 'None' for every user.

### ISSUE THREAD

**Issue by doctortickle** [mmohades/Venmo#4]
I am unable to obtain phone numbers for any users, to include my own.

```
venmo = Client(access_token=access_token)
me = venmo.user.get_my_profile()
myid = me.id

for user in venmo.user.get_user_friends_list(myid):
    print(user.phone)
```
Output:
```
None
None
None
None
...
```

**Comment by mmohades** [comment]
That’s because phone number is a private information, and Venmo only gives phone number of your own profile. Therefore, for everyone else, it’ll be None.
I mentioned it in the commit message of the pull request’s merge.

**Comment by doctortickle** [comment]
Ah I missed that, thank you.
