### ISSUE TITLE
Unexpected Keyword "Page"

### ISSUE THREAD

**Issue by damanc7** [mmohades/Venmo#42]
` users = venmo.user.search_for_users(query="Peter",
                                     page=2)
Traceback (most recent call last):
  File "<input>", line 3, in <module>
TypeError: search_for_users() got an unexpected keyword argument 'page'`

**Comment by mmohades** [comment]
The API has been updated but the doc is still outdated. You may just call it like
`users = venmo.user.search_for_users(query="Peter")`
There is no `page` function argument anymore.
