### ISSUE TITLE
I am getting this error on running one the examples in your documentation Error: Invalid Json

### ISSUE THREAD

**Issue by tochimclaren** [mmohades/Venmo#62]
I literally pasting the code you added as example and I am getting errors, I want to payout multiple users, but I can't query the users model to get the user ID I can see the access token
The bottom of the traceback reads

venmo_api.models.exception.HttpCodeError: HTTP Status code is invalid. Could not make the request because -> 503 Service Temporarily Unavailable.
Error: Invalid Json

**Comment by mmohades** [comment]
I think this might be related to [AWS outages](https://www.independent.co.uk/news/world/americas/amazon-down-outage-disney-venmo-b1971553.html).

**Comment by tochimclaren** [comment]
Thanks, that was the issue.
